name: dalal_street_client
description: Dalal Street Client for 2022
publish_to: "none"

version: 8.0.0+29

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Fonts

  google_fonts: ^2.1.1

  # Logging
  logger: ^1.1.0

  # Dependency Injection
  get_it: ^7.2.0

  # RxDart - For better control over streams (Cuz the default Dart Streams Api sucks)
  rxdart: ^0.27.3

  # gRPC
  grpc: ^3.0.2
  protobuf: ^2.0.0

  # Bloc - Stage Management
  bloc: ^8.0.1
  bloc_concurrency: ^0.2.0
  flutter_bloc: ^8.0.0
  # Hydrated Bloc
  hydrated_bloc: ^8.0.0
  path_provider: ^2.0.6

  # Needed for better state classes in Bloc
  equatable: ^2.0.3

  # Navigation
  go_router: ^3.0.1
  # Helper for matching path regex
  path_to_regexp: ^0.4.0

  # Form Validation
  reactive_forms: ^10.6.5

  # Other
  fixnum: ^1.0.0
  intl: ^0.17.0
  url_launcher: ^6.0.15
  super_tooltip: ^1.0.1
  flutter_svg: ^1.0.3
  flutter_spinbox: ^0.8.0
  pin_code_fields: ^7.3.0
  percent_indicator: ^3.4.0
  clipboard: ^0.1.3
  charts_flutter: ^0.12.0
  interactive_chart: ^0.3.4
  lottie: ^1.2.2
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
# Package for adding app icon uncomment these lines whenever we need to update the app icon
#   flutter_launcher_icons: "^0.9.2"

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/dalal_street_icon.png"

flutter:
  assets:
    - assets/icon/
    - assets/images/
    - assets/lottie/
    - assets/tls_keys/dev/server.crt
    - config.json

  uses-material-design: true
